builders:
    builder1:
      import: "package:generator_1/generator_1.dart"
      builder_factories: ["builder1"]
      build_extensions: {".dart": [".g.dart"]}
      auto_apply: dependents
      build_to: cache
      applies_builders: ["source_gen|combining_builder"]