name: generator_1
description:
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'
  flutter: ">=1.17.0"
dependency_overrides:
  analyzer: 5.10.0
dependencies:
  annotations_generator_1:
    path: ../annotations_generator_1/
  build: 2.3.1
  source_gen: 1.2.7
  analyzer: 5.10.0
  flutter:
    sdk: flutter
dev_dependencies:
