builders:
    builder2:
      import: "package:generator_2/generator_2.dart"
      builder_factories: ["builder2"]
      build_extensions: {".dart": [".g.dart"]}
      auto_apply: dependents
      build_to: cache
      applies_builders: ["source_gen|combining_builder"]